### ISSUE TITLE
Deprecated message "getEntityManager is deprecated since Symfony 2.1"

### ISSUE THREAD

**Issue by Mohammadtrabelsi** [doctrine/DoctrineBundle#602] opened 2016-12-19 14:15 UTC
I work with symfony "3.1.6" and i user doctrine/doctrine-bundle"1.6.4" and in the production environment, I got this message :

>   getEntityManager is deprecated since Symfony 2.1. Use getManager instead in projet/myprojectname/vendor/doctrine/doctrine-bundle/Registry.php

**Comment by stof** [comment] 2016-12-19 14:26
Well, audit your codebase to find the place calling the ``getEntityManager`` method of the registry.
The registry is the place telling you about the deprecation (we should update the message btw, as this code was extracted out of Symfony itself so talking about the Symfony version does not make sense)

**Comment by Mohammadtrabelsi** [comment] 2016-12-20 08:48
lhe call of **getEntityManager** is on 
> vendor/doctrine/doctrine-bundle/Command/ImportMappingDoctrineCommand.php
this is the method :

 

>      /**
>      * {@inheritDoc}
>      */
>     protected function execute(InputInterface $input, OutputInterface $output)
>     {
>         $bundle = $this->getApplication()->getKernel()->getBundle($input->getArgument('bundle'));
> 
>         $destPath = $bundle->getPath();
>         $type = $input->getArgument('mapping-type') ? $input->getArgument('mapping-type') : 'xml';
>         if ('annotation' === $type) {
>             $destPath .= '/Entity';
>         } else {
>             $destPath .= '/Resources/config/doctrine';
>         }
>         if ('yaml' === $type) {
>             $type = 'yml';
>         }
> 
>         $cme = new ClassMetadataExporter();
>         $exporter = $cme->getExporter($type);
>         $exporter->setOverwriteExistingFiles($input->getOption('force'));
> 
>         if ('annotation' === $type) {
>             $entityGenerator = $this->getEntityGenerator();
>             $exporter->setEntityGenerator($entityGenerator);
>         }
> 
>         $em = $this->getEntityManager($input->getOption('em'));
> 
>         $databaseDriver = new DatabaseDriver($em->getConnection()->getSchemaManager());
>         $em->getConfiguration()->setMetadataDriverImpl($databaseDriver);
> 
>         $emName = $input->getOption('em');
>         $emName = $emName ? $emName : 'default';
> 
>         $cmf = new DisconnectedClassMetadataFactory();
>         $cmf->setEntityManager($em);
>         $metadata = $cmf->getAllMetadata();
>         $metadata = MetadataFilter::filter($metadata, $input->getOption('filter'));
>         if ($metadata) {
>             $output->writeln(sprintf('Importing mapping information from "<info>%s</info>" entity manager', $emName));
>             foreach ($metadata as $class) {
>                 $className = $class->name;
>                 $class->name = $bundle->getNamespace().'\\Entity\\'.$className;
>                 if ('annotation' === $type) {
>                     $path = $destPath.'/'.str_replace('\\', '.', $className).'.php';
>                 } else {
>                     $path = $destPath.'/'.str_replace('\\', '.', $className).'.orm.'.$type;
>                 }
>                 $output->writeln(sprintf('  > writing <comment>%s</comment>', $path));
>                 $code = $exporter->exportClassMetadata($class);
>                 if (!is_dir($dir = dirname($path))) {
>                     mkdir($dir, 0775, true);
>                 }
>                 file_put_contents($path, $code);
>                 chmod($path, 0664);
>             }
> 
>             return 0;
>         } else {
>             $output->writeln('Database does not have any mapping information.', 'ERROR');
>             $output->writeln('', 'ERROR');
> 
>             return 1;
>         }
>     }

**Comment by stof** [comment] 2016-12-20 09:05
no, this is a call to ``getEntityManager`` on a totally different class. And this method does not use the deprecated API internally but the new API: https://github.com/doctrine/DoctrineBundle/blob/1.6.4/Command/DoctrineCommand.php#L58

**Comment by mikeSimonson** [comment] 2016-12-20 10:27
@Mohammadtrabelsi You need to look in your code (or another dependency) what calls $doctrineBundleRegistry->getEntityManager().

Closing as the issue is not in doctrineBundle

**Closed by mikeSimonson** 2016-12-20 10:27 UTC
