### ISSUE TITLE
Implement a DBAL middleware for the profiler collector

### ISSUE THREAD

**Issue by stof** [doctrine/DoctrineBundle#1431] opened 2021-11-23 16:29 UTC
Follows doctrine/dbal#4967

Maybe the Stopwatch integration should be a separate middleware than the collection of queries for the doctrine dbal panel.
Currently, we rely on a special SQLLogger to do that.

Refs #1429

**Comment by ostrolucky** [comment] 2021-11-23 16:42
Duplicate of https://github.com/doctrine/DoctrineBundle/issues/1429?

**Comment by stof** [comment] 2021-11-23 16:48
No. currently, our logger configuration covers 2 things:

- wiring the Psr3Logger to send queries to the `logger` service of Symfony
- wiring the special loggers related to the profiler (only when the profiler integration is enabled)

#1429 is about replacing the first part by wiring the logging middleware shipped in DBAL 3.2+.
this ticket is about *implementing* the necessary ProfilingMiddleware (or whatever its name) and using it instead of the special loggers, to replace the second part.

So they are related, but not duplicate (see how I even referenced it in the description)

**Comment by stof** [comment] 2022-03-30 08:39
The middleware is implemented in https://github.com/symfony/symfony/pull/45491

So it should be wired instead of the DbalLogger on supported Symfony and DBAL versions.

**Comment by dmaicher** [comment] 2022-06-06 16:30
done in https://github.com/doctrine/DoctrineBundle/pull/1517

**Closed as completed by dmaicher** 2022-06-06 16:30 UTC
Labels: Improvement, Ready to work on
