### ISSUE TITLE
Unit tests create a \"test\" file in project folder when run.

### ISSUE THREAD

**Issue by DHager** [doctrine/DoctrineBundle#433] opened 2015-06-06 03:20 UTC
@mikeSimonson : Moving my previous code-comment to this issue.

I'm seeing a new `"test"` file (with quotes) being created in my working directory every time I run unit tests. I suspect [this commit](https://github.com/doctrine/DoctrineBundle/commit/951f5f07d9a10f4bb82f166e8abcf271593f9e27) introduced it, causing the sqlite code to create an empty file.

It's easy to trace what's going on if you change the permission on the file so that nobody can read or write to it, which will cause the unit-test to fail and throw an exception. (e.g. with `chmod ugo-rw \"test\"` )

Can we clean this up so that the file isn't created or else goes into a system-appropriate temporary directory instead?

**Comment by mikeSimonson** [comment] 2015-06-06 06:44
If you can make a patch that avoid creating that file, you are most welcome.
I have no idea what is creating it exactly.

**Comment by DHager** [comment] 2015-06-08 17:31
It seems that the test is passing a `"memory"=>true` parameter, but the https://github.com/doctrine/dbal/blob/32b1a4f85a078f67752851c27be4065071db1f8b/lib/Doctrine/DBAL/Schema/SqliteSchemaManager.php isn't honoring it.

The extra-quotes in the filename are another matter, caused by `quoteSingleIdentifier()` being called.

**Comment by mikeSimonson** [comment] 2015-06-08 18:54
It's weird when I read the documentation I have the impression that this option is documented no ?
http://doctrine-dbal.readthedocs.org/en/latest/reference/configuration.html#pdo-sqlite

**Comment by DHager** [comment] 2015-06-08 19:35
Yeah, I'm working on [a possible fix](https://github.com/doctrine/dbal/compare/master...DHager:fix_sqlite_memory_db).

**Comment by mikeSimonson** [comment] 2015-06-09 20:14
@DHager Is there a reason why you did not made your pull request yet ?

**Comment by DHager** [comment] 2015-06-09 20:57
While it prevents the erroneous `"test"` file, it isn't *useful* anywhere beyond that, because new database in memory is immediately destroyed at the end of the same method, when `$conn->close()` is called.

**Comment by mikeSimonson** [comment] 2015-06-10 08:45
same result if you replace the ```'memory' => true ``` by ```'path' => ':memory:'``` ?

**Comment by ajcerqueti** [comment] 2015-11-23 17:41
+1 for fixing this. Mild inconvenience, but it's a pain. Still exists in 1.6.0 release. Happy to work on this if I can trace the cause. Came across it when running Symfony unit tests, so
```
 php app/console doctrine:database:create --env-test
```
creates a `"test.db"` file when `test.db` is expected. Only noticed because my .gitignore file is set-up to disregard the expected file, ran some tests an noticed the new filename when I was about to commit. The easiest solution is just to add the new file to .gitignore, but that's not solving anything!

**Comment by kimhemsoe** [comment] 2018-04-06 16:18
Yes, this should have been fixed. Closing.

**Closed by kimhemsoe** 2018-04-06 16:18 UTC
