### ISSUE TITLE
Upgrade to SF3.4

### ISSUE THREAD

**Issue by pdias** [doctrine/DoctrineBundle#742] opened 2017-12-03 17:57 UTC
After upgrade to SF3.4 i have this warning:

> The "doctrine.orm.default_entity_manager" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0

Thanks,

Paulo Dias

**Comment by pdias** [comment] 2017-12-03 18:51
But the strange thing is that when I execute

`debug: container doctrine.orm.default_entity_manager`

I get this:

> Information for Service "doctrine.orm.default_entity_manager"
> =============================================================
> 
>  ---------------- ------------------------------------------------------------------------------------------------------- 
>   Option           Value                                                                                                  
>  ---------------- ------------------------------------------------------------------------------------------------------- 
>   Service ID       doctrine.orm.default_entity_manager                                                                    
>   Class            EntityManager5a24454f0f59f_546a8d27f194334ee012bfe64f629947b07e4919\__CG__\Doctrine\ORM\EntityManager  
>   Tags             -                                                                                                      
>   Public           yes                                                                                                    
>   Synthetic        no                                                                                                     
>   Lazy             no                                                                                                     
>   Shared           yes                                                                                                    
>   Abstract         no                                                                                                     
>   Autowired        no                                                                                                     
>   Autoconfigured   no                                                                                                     
>   Required File    ....\var\cache\dev/jms_diextra/doctrine/EntityManager_5a24454f0f59f.php                      
>  ---------------- -------------------------------------------------------------------------------------------------------

And how can we verify the service is public.

**Comment by alcaeus** [comment] 2017-12-04 06:58
Which version are you using? The service is explicitly marked public in the latest version, so this shouldn't happen to you then.

**Comment by pdias** [comment] 2017-12-04 09:52
I'm using version 1.8.1

Yes the service is public, the command 

> debug:container doctrine.orm.default_entity_manager

this command shows this.

**Comment by alcaeus** [comment] 2017-12-04 15:58
I'm not sure why you're receiving an error in that case. Maybe @weaverryan or @nicolas-grekas know what's going on.

**Comment by nicolas-grekas** [comment] 2017-12-04 16:07
What the message says: it's public on 3.4 but will be private on 4.0.

**Comment by alcaeus** [comment] 2017-12-04 16:21
That doesn’t make any sense: https://github.com/doctrine/DoctrineBundle/blob/312ed029254c8753dca4c38571e0f8ca1e5350ea/DependencyInjection/DoctrineExtension.php#L512

**Comment by nicolas-grekas** [comment] 2017-12-04 16:39
It must make sense, for some reason we need to discover :)
A reproducer would help I guess.

**Comment by pdias** [comment] 2017-12-04 17:14
Yes don't make sense.

This is the trace:

User Deprecated: The "doctrine.orm.default_entity_manager" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
Show context    Hide trace

```
{▼
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php:275 {▼
    › if (isset($this->privates[$id])) {\r
    ›     @trigger_error(sprintf('The "%s" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.', $id), E_USER_DEPRECATED);\r
    › }\r
  }
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Bridge\Doctrine\ManagerRegistry.php:49 {▶}
  D:\wamp\www\My\vendor\doctrine\common\lib\Doctrine\Common\Persistence\AbstractManagerRegistry.php:231 {▶}
  D:\wamp\www\My\vendor\doctrine\doctrine-bundle\DataCollector\DoctrineDataCollector.php:66 {▶}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Profiler\Profiler.php:165 {▶}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\ProfilerListener.php:91 {▶}
  Symfony\Component\HttpKernel\EventListener\ProfilerListener->onKernelResponse() {}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\WrappedListener.php:104 {▶}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php:212 {▶}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php:44 {▶}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher.php:139 {▶}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:193 {▶}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:175 {▶}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:68 {▶}
  D:\wamp\www\My\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:202 {▶}
  D:\wamp\www\My\public_html\app_dev.php:29 {▼
    › $request = Request::createFromGlobals();
    › $response = $kernel->handle($request);
    › $response->send();
  }
}

```

I I'll try to debug ...

**Comment by stof** [comment] 2017-12-04 17:23
Looking at the info you provide above in your debug info, it looks like your `doctrine.orm.default_entity_manager` is actually the JMSDIExtraBundle proxy replacing the Doctrine service.
So this bug is in JMSDIExtraBundle, which does not properly preserve the service visibility when overwriting the service.

I'm closing this issue as it is not an issue in DoctrineBundle itself.

**Closed by stof** 2017-12-04 17:23 UTC

**Comment by alcaeus** [comment] 2017-12-04 17:36
Thanks @stof!

**Comment by pdias** [comment] 2017-12-04 18:24
Thansk @stof .

Just for testing, i set in config of JMSDIExtraBundle **doctrine_integration** to false and **no warning**.
