### ISSUE TITLE
`enable_lazy_ghost_objects: true` breaks separation of entities with serializer groups

### ISSUE THREAD

**Issue by Seesicht-IT** [doctrine/DoctrineBundle#1789] opened 2024-04-05 07:07 UTC
I recently updated my Symfony project from version 5.4 to 6.4. With this change, I also added `enable_lazy_ghost_objects: true` in the doctrine.yaml file.

Setting `enable_lazy_ghost_objects: false`, the existing code still runs perfectly fine.

With setting it to true, I get an error message like this:
```
An exception has been thrown during the rendering of a template ("Ignore on "Proxies\__CG__\App\Entity\Template::__setInitialized()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".").
```

I read the other comments about this new feature, but I don't understand, why it breaks my code.

I tried to hunt down the problem to this basic example:

Entity `Branch`
```
<?php

namespace App\Entity;

use App\Repository\BranchRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Groups;

/**
 * Branch.
 */
#[ORM\Table(name: 'branch')]
#[ORM\Entity(repositoryClass: BranchRepository::class)]
class Branch
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'id', type: 'integer')]
    #[Groups('branch')]
    private ?int $id = null;

    #[ORM\Column(name: 'filiale_nr', type: 'integer', unique: true, nullable: false)]
    #[Groups('branch')]
    private ?int $number = null;

    #[ORM\Column(name: 'filiale_name', type: 'string', length: 250, nullable: false)]
    #[Groups('branch')]
    private ?string $name = null;

    ...

    #[ORM\ManyToOne(targetEntity: BranchGroup::class, inversedBy: 'branches')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups('branch:branchGroup')]
    private ?BranchGroup $branchGroup = null;

    #[ORM\OneToMany(mappedBy: 'branch', targetEntity: Device::class)]
    #[Groups('branch:device')]
    private Collection $devices;

    #[ORM\OneToMany(mappedBy: 'branch', targetEntity: Warehouse::class, cascade: ['persist', 'remove'], fetch: 'LAZY')]
    #[ORM\JoinColumn(name: 'id', referencedColumnName: 'id')]
    #[Groups('branch:warehouse')]
    private Collection $warehouse;

    #[ORM\ManyToOne]
    #[Groups('branch:template')]
    private ?Template $template = null;

    #[ORM\ManyToOne]
    #[Groups('branch:printer')]
    private ?Printer $printer = null;

    public function __construct()
    {
        $this->devices = new ArrayCollection();
        $this->warehouse = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    ...

    public function getBranchGroup(): ?BranchGroup
    {
        return $this->branchGroup;
    }

    public function setBranchGroup(?BranchGroup $branchGroup): self
    {
        $this->branchGroup = $branchGroup;

        return $this;
    }

    public function getDevices(): Collection
    {
        return $this->devices;
    }

    public function addDevice(Device $device): self
    {
        if (!$this->devices->contains($device)) {
            $this->devices[] = $device;
            $device->setBranch($this);
        }

        return $this;
    }

    public function removeDevice(Device $device): self
    {
        if ($this->devices->removeElement($device)) {
            // set the owning side to null (unless already changed)
            if ($device->getBranch() === $this) {
                $device->setBranch(null);
            }
        }

        return $this;
    }

    public function setWarehouse(Warehouse $warehouse): void
    {
        $this->warehouse = new ArrayCollection([$warehouse]);
    }

    public function getWarehouse(): ?Warehouse
    {
        return $this->warehouse->isEmpty() ? null : $this->warehouse->first();
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(?Template $template): self
    {
        $this->template = $template;

        return $this;
    }

    public function getPrinter(): ?Printer
    {
        return $this->printer;
    }

    public function setPrinter(?Printer $printer): self
    {
        $this->printer = $printer;

        return $this;
    }
}
```
Entity `Template`
```
<?php

namespace App\Entity;

use App\Repository\TemplateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Groups;

#[ORM\Entity(repositoryClass: TemplateRepository::class)]
class Template
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Groups(['template', 'template_no_data'])]
    private ?int $id = null;

    #[ORM\Column(type: 'smallint')]
    #[Groups(['template', 'template_no_data'])]
    private ?int $number = null;

    #[ORM\Column(type: 'string', length: 50)]
    #[Groups(['template', 'template_no_data'])]
    private ?string $name = null;

    ...

    #[ORM\ManyToOne(targetEntity: TemplateType::class, inversedBy: 'templates')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups('template:templateType')]
    private ?TemplateType $templateType = null;

    #[ORM\OneToMany(mappedBy: 'template', targetEntity: DeviceModuleTemplatePrinter::class)]
    #[Groups('template:deviceModuleTemplatePrinter')]
    private Collection $deviceModuleTemplatePrinters;

    public function __construct()
    {
        $this->deviceModuleTemplatePrinters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    
    ...

    public function getTemplateType(): ?TemplateType
    {
        return $this->templateType;
    }

    public function setTemplateType(?TemplateType $templateType): self
    {
        $this->templateType = $templateType;

        return $this;
    }

    public function getDeviceModuleTemplatePrinters(): Collection
    {
        return $this->deviceModuleTemplatePrinters;
    }

    public function addDeviceModuleTemplatePrinter(DeviceModuleTemplatePrinter $deviceModuleTemplatePrinter): self
    {
        if (!$this->deviceModuleTemplatePrinters->contains($deviceModuleTemplatePrinter)) {
            $this->deviceModuleTemplatePrinters[] = $deviceModuleTemplatePrinter;
            $deviceModuleTemplatePrinter->setTemplate($this);
        }

        return $this;
    }

    public function removeDeviceModuleTemplatePrinter(DeviceModuleTemplatePrinter $deviceModuleTemplatePrinter): self
    {
        if ($this->deviceModuleTemplatePrinters->removeElement($deviceModuleTemplatePrinter)) {
            // set the owning side to null (unless already changed)
            if ($deviceModuleTemplatePrinter->getTemplate() === $this) {
                $deviceModuleTemplatePrinter->setTemplate(null);
            }
        }

        return $this;
    }
}
```
There is a ManyToOne relation between Branch and Template, but there is no "reverse" relation from Template to Branch.

I am using the Groups-attributes to control, which elements are actually required for which purpose in the code and also to not run into circular references.

I then have a really basic controller route for testing / understanding the problem:
```
#[Route(path: '/ghost-proxy', name: 'ghost_proxy')]
    public function testGhostProxy(EntityManagerInterface $entityManager): Response
    {
        $branches = $entityManager->getRepository(Branch::class)->findBy([], ['number' => 'ASC']);
        $templates = $entityManager->getRepository(Template::class)->findAll();

        return $this->render('app_dev/dist_control/control.html.twig', [
            'branches' => $branches,
            'templates' => $templates,
            'page_title' => 'Geräte',
            'nav_level_1' => 80,
            'nav_level_2' => 1,
        ]);
    }
```
And in the Twig-template I output `templates`and `branches`like this:
```
    <script type="text/javascript">
      const templates = JSON.parse('{{ templates|serialize('json', { groups: 'template'})|escape('js') }}');
      const branches = JSON.parse('{{ branches|serialize('json', { groups: 'branch'})|raw }}');
    </script>
```
Which then gives me the error message:
```
An exception has been thrown during the rendering of a template ("Ignore on "Proxies\__CG__\App\Entity\Template::__setInitialized()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".").
```

The problem is not specific to the entities `Branch` and `Template`. E.g. there is also a ManyToOne-relation between `Template`and `TemplateType`, which exists on both sides (OneToMany-relation between `TemplateType`and `Template`) and I get this error, when outputting those:
```
An exception has been thrown during the rendering of a template ("Ignore on "Proxies\__CG__\App\Entity\TemplateType::__setInitialized()" cannot be added. Ignore can only be added on methods beginning with "get", "is", "has" or "set".").
```

**I am by far no expert, so I assume that my code is wrong. Any suggestions are really appreciated!**

I am using these versions:
+ doctrine/annotations: 2.0.1
+ doctrine/dbal: 3.8.3
+ doctrine/doctrine-bundle: 2.12.0
+ doctrine/doctrine-migrations-bundle: 3.3.0
+ doctrine/orm: 2.19.3

**Comment by nicolas-grekas** [comment] 2024-04-05 07:19
Closing as duplicate of https://github.com/symfony/symfony/issues/54477
See https://github.com/symfony/symfony/pull/54485 for a tentative fix.

**Closed as completed by nicolas-grekas** 2024-04-05 07:19 UTC
