### ISSUE TITLE
Segmentation fault during PhpUnit run

### ISSUE THREAD

**Issue by EmanuelOster** [doctrine/DoctrineBundle#1080] opened 2019-11-28 11:05 UTC
After upgrading from Version 2.0.0 to 2.0.2 I got segmentation faults while running my tests.
Some testing then pinned it down to Version 2.0.1
Perhaps there is a connection to https://github.com/symfony/symfony/issues/34368.

I can also confirm that using the current dev-Version (Including this fix: https://github.com/symfony/symfony/pull/34580/files ) of symfony/http-kernel resolves the problem for me. However it does not seem to resolve the issue completely (as COil mentioned in his bugreport) and perhaps the issue here can help in pinning it down for good.

**Comment by alcaeus** [comment] 2019-11-28 11:36
The main change in 2.0.1 was changing the caching, which sounds like the linked PR works on.

> perhaps the issue here can help in pinning it down for good.

That's highly doubtful, especially considering that the cause of the segfault has been identified (albeit not fixed in all instances). I'm closing this issue as there's nothing we can do here (from what I can tell right now).

**Closed by alcaeus** 2019-11-28 11:36 UTC
