### ISSUE TITLE
[Postgres] Problem generating IDs with version 2.3.0

### ISSUE THREAD

**Issue by Nyholm** [doctrine/DoctrineBundle#1359] opened 2021-06-01 16:19 UTC
I have a strange bug that only shows in production for some reason. It seams like the auto generate ID feature is broken for some reason. 

I've done some testing back and forth in this repo: https://github.com/symfony-tools/carsonbot/issues/179

The error is basically: 

> An exception occurred while executing 'INSERT INTO task (repository_full_name, number, action, created_at, updated_at, verify_after) VALUES (?, ?, ?, ?, ?, ?)' with params ["carsonbot-playground\/symfony", 22, 4, "2021-05-31 14:10:11", "2021-05-31 14:10:11", "2021-06-01 10:10:11"]

The entity is found here: https://github.com/symfony-tools/carsonbot/blob/master/src/Entity/Task.php

The `id` column is not even in the SQL. 

As you can see from the history in https://github.com/symfony-tools/carsonbot/issues/179, I've limited the issue to this patch: https://github.com/doctrine/DoctrineBundle/compare/2.2.4...2.3.0

**Comment by ostrolucky** [comment] 2021-06-01 17:28
Probably caused by https://github.com/doctrine/DoctrineBundle/pull/1260, that's the only PR I know of which changes behaviour in prod mode. You can find more of such edge cases related to that improvement. We would welcome some community effort here to fix it.

In 2.4 we at least removed this optimization when `metadata_cache_driver` key is defined. But you will get deprecation and eventually run into the issue again, at least in doctrine-bundle 3.0.

cc @ossinkine

**Comment by oliver-schulz** [comment] 2021-06-02 18:05
Not sure if this helps but we had exactly the same problem here in prod.
Did you check what `doctrine:migration:diff` created? in our case there was a change detected and wanted to create some sequences and stuff like this.

We are using postrges and this bundle in version `2.3.2`. 

We also discovered a strange thing. When building our container for deployment, we had to call `cache:clear` but without `DATABASE_URL` set in this stage, so in this stage we don't have a "active" DB connection. In our case, the cache folder from the build process was not cleared before the container gets deployed. So the Container did run with the cache from the build process. What we now discovered. The cache file created in the build process `var/cache/prod/doctrine/orm/default_metadata.php` had a totally wrong `generatorType` setting.  When having  `DATABASE_URL` set, everything is fine.

**Comment by Nyholm** [comment] 2021-06-02 18:28
Thank you @oliver-schulz. I saw your slack conversation. 

I've managed to reproduce this. I basically warm the cache with a `sqlite` DSN and then use a `postgres` DSN in production. 
Of course, this is not optimal. But it was a something that was working on 2.2.4 and now silently fails. 

Im not sure how/if this should be fixed. Im just trying to add context.

**Comment by oliver-schulz** [comment] 2021-06-02 18:40
We have now changed our deployment and added a additional step, right before the container is exposed and after the container is running. We are calling the cache:warmup command to get a valid cache. But yes, this "bug" took me a day :)

**Comment by bendavies** [comment] 2021-06-03 09:08
We encountered a similar issue after upgrading DoctrineBundle from 2.2.4 to 2.3.1.

Unfortunately I can't confirm the issue was definitely that upgrade, as other dependencies were updated at the same time (which I then had to back out wholesale as we only saw the error in prod).

Our error was an incorrect ID being used in a insert statement, rather than no ID like in the OP.

1. Parent Record is inserted, returning auto int PK 2000.
2. Child record is inserted, which should use 2000 as the FK to Parent row, but uses some other ID which doesn't exist, like 2456, at which point PostgreSQL obviously throws an error for a non existent relation.

**Comment by alcaeus** [comment] 2021-06-16 06:22
@bendavies not sure if it's related, but do you by any chance warm up the cache in an environment with a different database than what's running in production?

**Comment by oliver-schulz** [comment] 2021-06-16 07:16
@bendavies Check also your ORM Annotations, since 2.3.X we discovered the Implementation is more strict, we also found some bugs in our entities, but this was caused by a wrong ORM annotation which we did not discover before the update. You can also use profiler->doctrine to get a info if you have problematic configurations.

**Comment by bendavies** [comment] 2021-06-16 09:33
@alcaeus yes, we were priming the cache with a url of `serverVersion=12`, which omitted the driver, so the cache was being warmed with mysql (the default) metadata instead of postgres.

**Comment by alcaeus** [comment] 2021-06-30 13:28
Closing since these issues all seem to have caused by running the cache warmup with a different configuration than the application is being run in.

**Closed as completed by alcaeus** 2021-06-30 13:28 UTC
