### ISSUE TITLE
"Division by zero" Error in DoctrineDataCollector

### ISSUE THREAD

**Issue by davewwww** [doctrine/DoctrineBundle#664] opened 2017-05-29 14:01 UTC
Got a "Division by zero" Error in DoctrineDataCollector->getGroupedQueries() when $totalExecutionMS is 0.

```
$groupedQueries[$connection][$i]['executionPercent'] = $query['executionMS'] / $totalExecutionMS * 100;
```

should be
```
$groupedQueries[$connection][$i]['executionPercent'] = $totalExecutionMS > 0 ? $query['executionMS'] / $totalExecutionMS * 100 : 0;
```

**Comment by Ocramius** [comment] 2017-05-29 14:15
Duplicate of #647 and #659 ?

**Comment by davewwww** [comment] 2017-05-29 14:17
oh, yes. 
sorry for repost.

**Closed** 2017-05-29 14:18 UTC
