### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by andreybolonin** [doctrine/DoctrineBundle#667] opened 2017-05-31 18:27 UTC
```
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /home/andreybolonin/www/CRUDsymfony/vendor/doctrine/doctrine-bundle/Tests/TestCase.php on line 24
PHP Stack trace:
PHP   1. {main}() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/phpunit:53
PHP   3. PHPUnit\TextUI\Command->run() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/src/TextUI/Command.php:140
PHP   4. PHPUnit\TextUI\Command->handleArguments() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/src/TextUI/Command.php:151
PHP   5. PHPUnit\Util\Configuration->getTestSuiteConfiguration() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/src/TextUI/Command.php:779
PHP   6. PHPUnit\Util\Configuration->getTestSuite() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/src/Util/Configuration.php:867
PHP   7. PHPUnit\Framework\TestSuite->addTestFiles() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/src/Util/Configuration.php:971
PHP   8. PHPUnit\Framework\TestSuite->addTestFile() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/src/Framework/TestSuite.php:394
PHP   9. PHPUnit\Util\Fileloader::checkAndLoad() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/src/Framework/TestSuite.php:322
PHP  10. PHPUnit\Util\Fileloader::load() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/src/Util/Fileloader.php:45
PHP  11. include_once() /home/andreybolonin/www/CRUDsymfony/vendor/phpunit/phpunit/src/Util/Fileloader.php:61
PHP  12. spl_autoload_call() /home/andreybolonin/www/CRUDsymfony/tests/AppBundle/ArticleTest.php:7
PHP  13. Composer\Autoload\ClassLoader->loadClass() /home/andreybolonin/www/CRUDsymfony/tests/AppBundle/ArticleTest.php:7
PHP  14. Composer\Autoload\includeFile() /home/andreybolonin/www/CRUDsymfony/vendor/composer/ClassLoader.php:322
PHP  15. include() /home/andreybolonin/www/CRUDsymfony/vendor/composer/ClassLoader.php:444

```

**Comment by Ocramius** [comment] 2017-05-31 18:28
> What is this? 

A crash that is unrelated to this project ;-)

**Comment by alcaeus** [comment] 2017-05-31 18:31
That's an exception due to a version constraint on PHPUnit that is too loose. `~4` in composer.json also allows PHPUnit 6, which no longer has the class in question. The constraint should most probably be updated to only allow PHPUnit 5.x. Alternatively, it may allow 5.7 and 6.x, but that requires replacing `PHPUnit_Framework_TestCase` with `PHPUnit\Framework\TestCase`.

**Comment by Ocramius** [comment] 2017-05-31 18:34
I was too quick on this one, sorry! 

Still, since I was looking at `/home/andreybolonin/www/CRUDsymfony` in your trace, I assumed you weren't affected by our defined dev dependencies? Do you have a way to reproduce this?

**Comment by Ocramius** [comment] 2017-05-31 18:43
Checked locally: `~4` is equivalent to `~4.0` and `^4`:

![5f3feb](https://cloud.githubusercontent.com/assets/154256/26648124/b6256a62-4641-11e7-9be1-d1012768e8d0.png)

Closing again, not caused here.

**Closed by Ocramius** 2017-05-31 18:43 UTC
