### ISSUE TITLE
[Bug] Division by zero in profiler

### ISSUE THREAD

**Issue by yoshi-1** [doctrine/DoctrineBundle#659] opened 2017-05-15 13:29 UTC
doctrine/doctrine-bundle - version: 1.6.7

Hello,
i'm facing an issue where there are 3 db calls when loading a page but none of them has an execution time larger than 0. This causes the profiler to throw a "Division by zero"-Exception:
`CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Warning: Division by zero")." at xxx\vendor\doctrine\doctrine-bundle\Resources\views\Collector\db.html.twig line 157 `  

It's caused by Doctrine\Bundle\DoctrineBundle\DataCollector\DoctrineDataCollector line 227
where a total execution time of 0ms isn't checked:
`$groupedQueries[$connection][$i]['executionPercent'] = $query['executionMS'] / $totalExecutionMS * 100;`

I don't know why the queries don't have any execution time set, but i'd say this shouldn't result in a div by zero.

Regards

**Comment by Ocramius** [comment] 2017-05-16 11:25
Duplicate of https://github.com/doctrine/DoctrineBundle/pull/647 and https://github.com/doctrine/DoctrineBundle/pull/647 ?

**Comment by yoshi-1** [comment] 2017-05-16 11:31
@Ocramius Yes, you're right. Sorry for dup.

**Comment by Ocramius** [comment] 2017-05-16 11:38
https://www.youtube.com/watch?v=4QWfrxYt9DQ

**Closed by Ocramius** 2017-05-16 11:38 UTC
Labels: Bug
