### ISSUE TITLE
[1.11] schema_filter configuration no longer works

### ISSUE THREAD

**Issue by enumag** [doctrine/DoctrineBundle#971] opened 2019-05-15 13:00 UTC
We have some Doctrine entities which are read only because they are mapped to views instead of regular tables. To prevent the tables from being generated by doctrine migrations we're using a configuration like this:

```yaml
doctrine:
    dbal:
        schema_filter: ~^(?!foo_view|bar_view)~
```

After updating to DoctrineBundle 1.11.1 this no longer works and doctrine/migrations is trying to generate normal tables for these entities.

**Comment by alcaeus** [comment] 2019-05-16 07:43
Could you please let me know what version of `doctrine/dbal` you have installed? You can find out by running `composer show doctrine/dbal`. This might be caused by #935 not correctly applying a regular expression filter to the new chain. #966 added a missing compiler pass registration, but since you mentioned you're using DoctrineBundle 1.11.1 this shouldn't be the issue.

There's also a test to make sure the filter is registered correctly (see https://github.com/doctrine/DoctrineBundle/blob/43e90873f24fb2d4b20714a1fc3a90e6a72a6733/Tests/DependencyInjection/AbstractDoctrineExtensionTest.php#L784) when the compiler pass is registered, so I'm not quite sure where the issue is coming from.

**Comment by keksa** [comment] 2019-05-16 08:24
Hello @alcaeus, we have the following doctrine packages installed:
```
doctrine/annotations - v1.6.1
doctrine/cache - v1.8.0
doctrine/collections - v1.6.1
doctrine/common - v2.10.0
doctrine/data-fixtures - v1.3.1
doctrine/dbal - v2.9.2
doctrine/doctrine-bundle - 1.11.1
doctrine/doctrine-cache-bundle - 1.3.5
doctrine/doctrine-migrations-bundle - v1.3.2
doctrine/event-manager - v1.0.0
doctrine/inflector - v1.3.0
doctrine/instantiator - 1.2.0
doctrine/lexer - v1.0.1
doctrine/migrations - v1.8.1
doctrine/orm - v2.6.3
doctrine/persistence - 1.1.1
doctrine/reflection - v1.0.0
doctrine/doctrine-fixtures-bundle - v2.4.1
```

**Comment by alcaeus** [comment] 2019-05-16 08:37
Hmm, that’s odd. Any chance you could debug this to see what’s going on? I currently don’t have a bundle setup.

**Comment by enumag** [comment] 2019-05-16 09:17
Can you give us some tips where to look? I've no idea where the schema_filter is *supposed* to be used.

**Comment by alcaeus** [comment] 2019-05-16 12:41
You should see a `doctrine.dbal.<connection-name>_regex_schema_filter` service that is tagged with the `doctrine.dbal.schema_filter` tag. There should also be a call to `setSchemaAssetsFilter` on the `doctrine.dbal.<connection-name>_connection.configuration` service with an argument that contains a `SchemaAssetsFilterManager` instance.

**Comment by enumag** [comment] 2019-05-17 06:49
`setSchemaAssetsFilter` is properly called with the correct filter. However the `RegexSchemaAssetFilter` is never even asked about the tables we want to ignore. Any ideas how that could have happened?

**Comment by enumag** [comment] 2019-05-17 07:04
Ok I checked back on the 1.10 version and the schema filter is never called there for the views we want to ignore either. Which means schema filter was not the thing that made them ignored. Something else must be broken.

**Comment by enumag** [comment] 2019-05-17 07:17
Hmm no it is the schema filter after all. When I remove the views from the schema filter the tables are generated by the next migration. However it's not [this line](https://github.com/doctrine/dbal/blob/4d0d2affceb800088f24904dd5aed316db97b145/lib/Doctrine/DBAL/Configuration.php#L111) that causes it. Which means the schema filter must be used somewhere else as well in the older version but the usage got removed in 1.11.

**Comment by enumag** [comment] 2019-05-17 07:42
I think I identified the problem. See the PR in doctrine/migrations.

**Comment by alcaeus** [comment] 2019-07-09 19:47
Closing as this was an issue in doctrine/migrations.

**Closed by alcaeus** 2019-07-09 19:47 UTC
