### ISSUE TITLE
Symfony  doctrine:schema:update not work

### ISSUE THREAD

**Issue by allfreelancers** [doctrine/DoctrineBundle#783] opened 2018-02-22 09:32 UTC
Hi all!
I am using symfony 3.4 and run:
```
php bin/console doctrine:schema:update --dump-sql
```
SQL generated:
```
ALTER TABLE specializations CHANGE parent parent BIGINT DEFAULT NULL;
```
I execute query in DB and have same sql again.

My table:
```
CREATE TABLE IF NOT EXISTS `specializations` (
`id` bigint(20) NOT NULL,
...
  `parent` bigint(20) DEFAULT NULL,
...
) ENGINE=InnoDB AUTO_INCREMENT=197 DEFAULT CHARSET=utf8;
```

what could be the problem?

10.2.10-MariaDB

**Comment by Ocramius** [comment] 2018-02-22 09:50
Dupe of https://github.com/doctrine/DoctrineBundle/issues/782 ?

**Comment by allfreelancers** [comment] 2018-02-22 09:51
@Ocramius I also think so, what solution?

**Comment by Ocramius** [comment] 2018-02-22 09:52
No solution yet, but closing as duplicate here.

**Closed by Ocramius** 2018-02-22 09:52 UTC
