### ISSUE TITLE
 Close connections and clear managers on shutdown should be *optional* in test mode

### ISSUE THREAD

**Issue by dvc** [doctrine/DoctrineBundle#407] opened 2015-03-26 06:52 UTC
Related to: #366 
Almost all our functional tests has been broken by #366 ! :(

Our project has very complex user-account-roles-subscriptions relations an hierarchy. And very complex bussiness objects inheritance and relations. It is a real pain to emulate realistic test environment... So, the decision for us:
1) Create maximum of dictionaries, users and user data at once, before all tests.
2) Instance one connection in setUp() and set it in custom Client and start transaction
3) It allows to test some multipage workflows, check data directly from server-side before/after any request and rollback all modifications in tearDown(). Fast and clear.

See http://alexandre-salome.fr/blog/Symfony2-Isolation-Of-Tests for details

This recipe doesn`t work after #366. 

Can you make this good functional configurable?

**Comment by hmillet** [comment] 2015-03-26 12:07
Got exactly the same trouble.

Using the same trick of Alexandre Salome to isolate my tests.

How to get a good new way to isolate our tests ?

**Comment by dvc** [comment] 2015-03-26 12:25
May be workaround to avoid new code:

```php
  # app/Kernel.php
    /**
     * Обходим принудительное закрытие коннекта
     *
     * @see https://github.com/doctrine/DoctrineBundle/issues/407
     *
     * {@inheritdoc}
     *
     * @api
     */
    public function shutdown()
    {
        if (false === $this->booted) {
            return;
        }

        $this->booted = false;

        foreach ($this->getBundles() as $bundle) {
            /**
             * Вмешиваемся только в один класс и только в тестовой среде окружения
             */
            if ($bundle instanceof Doctrine\Bundle\DoctrineBundle\DoctrineBundle && ('test' === $this->getEnvironment())) {
                /**
                 * Используем замыкание для доступа к приватной переменной DoctrineBundle->autoloader
                 * @see http://habrahabr.ru/post/186718/
                 */
                $doctrineShutdown = Closure::bind(
                    function () {
                        if (null !== $this->autoloader) {
                            spl_autoload_unregister($this->autoloader);
                            $this->autoloader = null;
                        }
                    },
                    $bundle,
                    'Doctrine\Bundle\DoctrineBundle\DoctrineBundle'
                );
                $doctrineShutdown();
            } else {
                $bundle->shutdown();
            }

            $bundle->setContainer(null);
        }

        $this->container = null;
    }

```

**Comment by hmillet** [comment] 2015-07-31 15:38
This workaround works for me, thanks a lot @dvc

**Comment by mtibben** [comment] 2015-09-02 05:58
I have the same problem. We run each test inside a transaction, which is rolled back on teardown. This keeps the test db in a clean state without the need to rebuild it for each test. 

When using symfony's test client to simulate http requests, after each request the kernel is shutdown which now means all connections are closed.

It would be nice if there was a way to avoid that.

**Comment by craue** [comment] 2016-02-25 10:28
I'm stuck on DoctrineBundle 1.3 because of this issue. It breaks a lot of my tests where assertions on entities are made.

**Comment by mtibben** [comment] 2016-02-25 12:15
I worked around the issue by decorating the connection in tests and noop
the close function

**Comment by craue** [comment] 2016-02-25 12:25
@mtibben, currently I'm calling `close` manually in `tearDown`, so noop-ing it is not an option. I tried @dvc's `shutdown` code and it would solve the issue, but I'd prefer a proper fix/feature instead of such a workaround.

**Comment by mtibben** [comment] 2016-02-25 23:26
Yeah to get around that I created a `rollbackTestTransactionAndClose` function - here's the code

```php
<?php

namespace AppBundle\Framework;

use Doctrine\DBAL\Connections\MasterSlaveConnection;
use Exception;

// Decorates a connection to disable $connection->close()
//
// Every test we run is isolated within a DB transaction.
//
// However Doctrine closes all connections on kernel shutdown.
//
// This is a problem because in some tests the kernel is booted
// and shutdown multiple times (e.g. when using the WebTest client)
// which means Doctrine is closing the active transaction
// established in TestDatabaseConnectionFactory
//
// To work around the issue we stop the connection from being closed
//
// Also see https://github.com/doctrine/DoctrineBundle/issues/407
class TestDatabaseConnection extends MasterSlaveConnection
{
    private $isTestTransactionCreated = false;

    public function connect($connectionName = null)
    {
        $result = parent::connect($connectionName);

        if ($result && $this->isConnectedToMaster() && !$this->isTestTransactionCreated) {
            $this->setNestTransactionsWithSavepoints(true);
            $this->beginTransaction();
            $this->isTestTransactionCreated = true;
        }

        return $result;
    }

    public function rollbackTestTransactionAndClose()
    {
        if ($this->isTestTransactionCreated) {
            $this->rollback();
            if ($this->isTransactionActive()) {
                throw new Exception("Didn't expect transaction to be active");
            }
        }

        parent::close();
    }

    public function close()
    {
        // no-op
    }
}
```

**Comment by dmaicher** [comment] 2019-04-09 19:37
The issue is quite old but I think this bundle will simplify all your transactional test logic quite a bit :wink: 

https://github.com/dmaicher/doctrine-test-bundle

**Comment by alcaeus** [comment] 2019-04-12 05:16
Closing as per https://github.com/doctrine/DoctrineBundle/issues/638#issuecomment-482438404.

**Closed by alcaeus** 2019-04-12 05:16 UTC
