### ISSUE TITLE
Doctrine schema update filter problem

### ISSUE THREAD

**Issue by PlamenVasilev** [doctrine/DoctrineBundle#551] opened 2016-06-21 13:02 UTC
I have a problem with excluding table from schema with symfony 2.8.5

According to this http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#manual-tables
I can exclude tables form schema diff and ignore them

When I set this filter to specific table 

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                schema_filter: ~^(?!table_name)~
```

and then run `php app/console doctrine:schema:update --dump-sql`

I see SQL for creation of the excluded table.
When I comment the schema_filter .. no DB changes will be made.

This option should not produce create/alter/drop statements for excluded tables or I'm wrong?

I have wrote to Symfony about this, by they said that this is  doctrine problem [https://github.com/symfony/symfony/issues/19076](url)

**Comment by kimhemsoe** [comment] 2016-06-21 13:13
The filter is applied when doctrine is looking at your database and not
your configured entities. I am guessing you have an entity with a table
name which gets filtered out by by the filter and doctrine will try to
create it as it believes it is missing.

**Comment by PlamenVasilev** [comment] 2016-06-21 13:20
I have an entity which is representation of DB table.
When I exclude this table doctrine is trying to create this table, but it exists.

I my case I'm using third party software tables and I have entities mapped to these tables.
I want to exclude these tables from schema create/update/drop

According to this
http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#manual-tables
the filter should exclude these tables ... by name or prefix ..

**Comment by PlamenVasilev** [comment] 2016-06-21 13:25
The strange thing here is that when I have entity which is 1:1 with the database and I run doctrine:schema:update --dump-sql the is no alter/create/drop
but when I exclude this table doctrine:schema:update --dump-sql prints create statement for this table.

**Comment by kimhemsoe** [comment] 2016-06-21 15:05
Filter does not work configured tables, only tables in the database.

If you have t1, t2, and t3 and your entities is configured to use t1,t2,t3 and t4. If you filter t2 doctrine sees t1 and t3 from the database, compares that with configured entities and sees that t2 and t4 is not created. It will created those tables for you.

So to sum up. Filter "hides" tables from the database from doctrine, it does not stop doctrine from trying to create these tables

**Comment by PlamenVasilev** [comment] 2016-06-22 06:05
OK, so what id the purpose of this filter if it will try to create t2 when it is excluded and is existing into the database ?

**Comment by kimhemsoe** [comment] 2016-06-22 07:42
The purpose of the filter is to hide tables from doctrine. If doctrine cant see the table but it is configured it will create the table ofc.

**Comment by PlamenVasilev** [comment] 2016-06-22 08:46
The there another way to tell doctrine not to create/alter/drop third party tables ?

**Comment by stof** [comment] 2016-06-22 08:50
@PlamenVasilev if you have an entity in your code, it is not a third party table, as Doctrine knows about it.
The filtering feature is precisely about avoiding to drop third party tables (i.e. tables which are in the same database but used by another system than the ORM)

**Comment by kimhemsoe** [comment] 2016-06-23 09:06
Closing. Not a bug.

**Closed by kimhemsoe** 2016-06-23 09:06 UTC

**Comment by helmuthva** [comment] 2016-12-29 17:11
hi @kimhemsoe,

Let's say we have tables managed (and created on setup) by Wordpress regular (all starting with wp_) and some nice Doctrine Entities that allow OO-access to these tables.

Setting the schema_filter option to ~^(?!wp_)~ filters out the Wordpress tables for 

doctrine:migrations:diff
doctrine:schema:drop

but not

doctrine:schema:create

which feels strange and leads to problems.

If you don't want to change the behaviour of schema_filter on doctrine:schema:create by default how about an option to at least trigger this behaviour for the ones of us that need that?

Best Regards

**Comment by mikeSimonson** [comment] 2016-12-30 07:51
The part that feels strange and leads to problem is that you are using doctrine to map table that are managed (and created) by wordpress and you expect doctrine to at the same time manage and not manage those table.

There is no sane solution here.
The only sane solution is that in that setup you need to know that you can't use doctrine:schema:create.

**Comment by Russellmd** [comment] 2022-09-07 12:43
> @PlamenVasilev if you have an entity in your code, it is not a third party table, as Doctrine knows about it. The filtering feature is precisely about avoiding to drop third party tables (i.e. tables which are in the same database but used by another system than the ORM)

What about the views/temporary tables used in the same system? I used them as entities with "read_only" option, it's convinient to use in join. And I have the same problem:  "schema_filter" work in migration process, but not with "doctrine:schema:update". As a result, on an environment initialization, views are created as normal tables...

**Comment by siggidiel** [comment] 2022-09-08 14:00
Unfortunately, we have the same issue during execution of integration tests and a temporary table. We are using `zenstruck/foundry` for integration tests and in order to reset the schema. It drops the schema and recreates it again for almost each test scenario. 
The problem is, that this `schema_filter` option inside the doctrine configuration is ignored by the schema manager and our TmpFooEntity is annotated with `@ORM\Entity()`. It tries to create it but fails because it already exists.

The schema manager would only ignore the entity if the annotation is removed. But then, our application is crashing when it comes to certain business logic.

We somehow need to hack the schema:create command in order to ignore temporary tables

**Comment by stof** [comment] 2022-09-08 14:13
@ServerExe the schema filter applies to the introspection of the existing database. It does not apply to the schema built from the mapping. If you want to remove some table from that schema (so that they are not created by Doctrine), you should use a listener on the `\Doctrine\ORM\Tools\ToolEvents::postGenerateSchema` Doctrine event to modify the Schema before it is used by Doctrine to compare it to the existing DB (in that listener, you can remove tables from the schema)

**Comment by siggidiel** [comment] 2022-09-08 16:24
> @ServerExe the schema filter applies to the introspection of the existing database. It does not apply to the schema built from the mapping. If you want to remove some table from that schema (so that they are not created by Doctrine), you should use a listener on the `\Doctrine\ORM\Tools\ToolEvents::postGenerateSchema` Doctrine event to modify the Schema before it is used by Doctrine to compare it to the existing DB (in that listener, you can remove tables from the schema)

Thanks! Fixed by doing the following:
````
class ToolEventsListener
{
    public const TMP_TABLE_NAME = 'your_desired_table';

    public function postGenerateSchema(GenerateSchemaEventArgs $eventArgs): void
    {
        $schema = $eventArgs->getSchema();

        // remove temporary table from schema before creating the tables
        try {
            $schema->dropTable(self::TMP_TABLE_NAME);
        } catch (SchemaException $e) {
            // do nothing if table is not found
        }
    }
}
````

Inside `services.yaml`:
````
App\Doctrine\ORM\Tools\EventListener\ToolEventsListener:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }
````
