### ISSUE TITLE
Upgrading to 2.8.2 has error Call to a member function getUnitOfWork() on null

### ISSUE THREAD

**Issue by madmortigan1** [doctrine/DoctrineBundle#1625] opened 2023-01-29 09:52 UTC
Hello,

Since adding the LazyGhostTrait the _em in EntityRepository throws the following error
Call to a member function getUnitOfWork() on null.
![image](https://user-images.githubusercontent.com/53225926/215318340-e656c7c4-b084-4b5e-82af-843f9f6aa40c.png)

I tried to pin point the issue to tell you more, all I can say is the following:
I have a repository extends ServiceEntityRepository.
Calling the parent "parent::__construct($registry, XXX:class);"  loads the 
class LazyServiceEntityRepository.

The result is that _em in class EntityRepository is always null.

Downgrading back to version 2.8.0 before the change works perfectly as before.
I did not find any changes in the documentations that needs to alter any config settings.

Please advice,
Regards,

**Comment by nicolas-grekas** [comment] 2023-01-29 09:56
Can you please provide a small reproducing app?

**Comment by madmortigan1** [comment] 2023-01-29 12:42
Does not reproduce on a new skeletal project, to take my project and summarize it down will take time I will not put in yet.

I am using php-fpm docker 8.2.1
Latest built of symfony 6.2.5

In the doctorine yaml, I have removed all the additional setup I had but it still does not work.
The only thing I could not change was the prefix of the project to check it.

Cleaning var/cache does not help
So far I am out of ideas
![image](https://user-images.githubusercontent.com/53225926/215326826-d54998bc-166f-4ca2-9b3d-35d96f0d49db.png)

**Comment by revenkroz** [comment] 2023-02-01 13:00
I had the same problem after the upgrade today. I went back to 2.7. I do not use any additional traits.

**Comment by nicolas-grekas** [comment] 2023-02-01 13:02
@revenkroz can you figure out a reproducer? "me too" comments are not really useful you know...
@madmortigan1 you might want to check the stack trace. Does it include a constructor? If yes, that constructor might be doing too much.

**Comment by revenkroz** [comment] 2023-02-01 19:48
@nicolas-grekas I apologize for not writing more information. I just wanted to draw attention.

I managed to find the cause — this happens when custom `Repository` is marked as `lazy` in the bundle configuration (e.g. `services.yaml`).

**Comment by madmortigan1** [comment] 2023-02-02 10:06
@revenkroz Well done finding the issue, all my repositories are lazy automatically.
The class ServiceEntityRepository that extends LazyServiceEntityRepository is the one that is loaded.

@nicolas-grekas For you question:
The constructor that is loaded is the one from LazyServiceEntityRepository  class:
![image](https://user-images.githubusercontent.com/53225926/216294804-50c80e45-7c3a-4743-904b-2c609842c904.png)

When I debugged, the _em was not null, but it is null when calling the repository and creating a query like find..

**Comment by nicolas-grekas** [comment] 2023-02-02 10:09
I'm talking about a constructor in your code :)
A reproducer would be really useful.

**Comment by madmortigan1** [comment] 2023-02-02 10:26
@nicolas-grekas 
My constructors are pretty plain, nothing happens in them other than calling parent:
I did try to call different repositories for testing and it happened in all of them.

![image](https://user-images.githubusercontent.com/53225926/216298934-e6c5c7c6-3b4f-4a04-a193-fcaaf56a2b68.png)

I know a reproducer would help, unfortunalty I spent a few hours trying to make you one and could not reproduce it, meaning something else is causing it that did not happen in a skeleton project.
I did not have the luck to pin point it yet.

Any advice from you for me to test and narrow it down would be very appreciated since I always do my best to be up to date with all the versions.

**Comment by madmortigan1** [comment] 2023-02-02 10:42
@nicolas-grekas 
I would like to add that you gave me an idea, and for testing purpose I removed the custom Repository and removed @ORM\ENTITY(repositoryClass...)  And it does not happen.
Meaning it happens only when there is a reference to a repository class.

**Comment by stof** [comment] 2023-02-02 15:07
@madmortigan1 can you check if this still happens with `2.8.x-dev` as version for the bundle ? There is a change merged but not released yet that is related to those proxies.

**Comment by madmortigan1** [comment] 2023-02-06 10:03
@stof @nicolas-grekas Good morning, I confirm that the dev works properly.
Thank you very much

**Comment by stof** [comment] 2023-02-06 10:08
Closing this issue then. I just released 2.8.3.

**Closed as completed by stof** 2023-02-06 10:08 UTC
Labels: Bug
