### ISSUE TITLE
Dependency ocramius/proxy-manager issue

### ISSUE THREAD

**Issue by mgascoyne** [doctrine/DoctrineBundle#1123] opened 2020-01-07 09:38 UTC
The dependency "ocramius/proxy-manager": "^2.1" has an dependency on "zendframework/zendcode": "^3.1.0" but this dependency is abandoned now.

**Comment by ostrolucky** [comment] 2020-01-07 09:42
Duplicate of https://github.com/Ocramius/ProxyManager/issues/551

**Closed by ostrolucky** 2020-01-07 09:42 UTC
