### ISSUE TITLE
BC break between 1.6.7 -> 1.6.8 regarding driver selection

### ISSUE THREAD

**Issue by Majkl578** [doctrine/DoctrineBundle#673] opened 2017-06-27 03:34 UTC
After upgrading from 1.6.7 to 1.6.8, all our tests started failing. While investigating, found that DBAL driver is somehow not picked up correctly.
All functional tests failing with:
```
Doctrine\DBAL\Exception\DriverException: An exception occured in driver: could not find driver
```

It suddenly tries to load pdo_mysql instead of pdo_pgsql.

Bisected this breakage to commit 99a62a7c4139c0ccb6969de5eff1447b1a6cbaf4.

This is what our DBAL config looks like:
```
doctrine:
    dbal:
        default_connection: xxx
        connections:
            xxx:
                server_version: 9.4
                driver: "%database_driver%"
                host: "%database_host%"
                port: "%database_port%"
                dbname: "%database_name%"
                user: "%database_user%"
                password: "%database_password%"
                charset: UTF8
                mapping_types:
                    bit: boolean
                    tsvector: string
        types:
            foo:
                class: X\Y\Types\FooType # <-- commented type
```

**Comment by Ocramius** [comment] 2017-06-27 05:19
Indeed, `$platform = $connection->getDatabasePlatform();` is the culprit here.

@mikeSimonson how much of an issue would a reversal of the bugfix be? I think this one is more critical...

**Comment by mikeSimonson** [comment] 2017-06-28 08:43
Does that mean that somehow the $connection->getDatabasePlatform(); call override the server version config value ? Reading the code it seems like it shouldn't be the case (it bails out if it's already set).

@Majkl578 Can you dig further with xdebug to see how that value gets changed ?

**Comment by stof** [comment] 2017-06-28 08:53
@mikeSimonson  `$connection->getDatabasePlatform()` needs to know the server version, to get the right platform. If you have not configured it explicitly in the config, DBAL tries to guess it, and that requires connecting to the server.

However, I don't see any reason for using MySQL (unless your project does weird thing changing the database config at runtime to move it from mysql to postgresql, and the code now connects before your magic.

@Ocramius I'm in favor of reverting the bugfix and deprecating the feature entirely. Marking a type as commented should be done in the Type class itself rather than in the bundle config (DBAL supports marking a type as commented in the Type itself since 2.4)

**Comment by mikeSimonson** [comment] 2017-06-28 20:39
Does that mean that somehow the $connection->getDatabasePlatform(); call override the server version config value ? Reading the code it seems like it shouldn't be the case (it bails out if it's already set).

@Majkl578 Can you dig further with xdebug to see how that value gets changed ?

**Comment by sebastianfeldmann** [comment] 2017-06-29 19:32
Hi the problem ist not with @mikeSimonson changes introduced with commit 99a62a7c4139c0ccb6969de5eff1447b1a6cbaf4

Applying the commented types even if no "un"commented types exist is a valid fix.

## Analysis
After consulting wit @Ocramius the assumption is, that because now `CommentedTypes` are always registered, doctrine tries to register them on the predefined default_connection.

<img width="310" alt="bundle" src="https://user-images.githubusercontent.com/9250358/27706035-4328df90-5d10-11e7-8c11-590871d465c8.png">

The problem is that we are now registering types on a connection we don't use, or in this case isn't woking at all.

## Solution
A solution would be to handle the type registration within DBAL but because of this breaking backwards compatibility the only thing we can do right now is to throw some more descriptive exception so the user understand the problem.

**Comment by Ocramius** [comment] 2017-06-29 19:40
Amazing analysis, thanks @sebastianfeldmann!

Closing this, as the original patch WAS correct.

@Majkl578 the problem is that your "generic connection" service still exists and is used in some services, even though the connection was never established before.

**Closed by Ocramius** 2017-06-29 19:40 UTC
Labels: Bug

**Comment by Majkl578** [comment] 2017-06-29 21:41
@sebastianfeldmann Good job there. In other words, 99a62a7 just exposed the _issue_ which was just hiding there previously... And now this is marked as an expected BC break in bugfix version...

Anyway, this behavior doesn't make any sense IMHO. I'm explicitly registering only one connection and default_connection points to this specific connection, so why is the bundle even trying to create a connection that was not requested or even used anywhere? (Also _driver_ defaulting to _pdo_mysql_ is just another crazy assumption, but that's different story.) 😕

**Comment by Ocramius** [comment] 2017-06-29 22:00
> why is the bundle even trying to create a connection that was not requested or even used anywhere?

Usually something referencing the service in a hardcoded way

**Comment by JustBlackBird** [comment] 2017-08-18 08:56
@Majkl578 Had you finally traced the reason why `doctrine.dbal.default_connection` is created? I have the same issue here and I almost sure the app does not require `doctrine.dbal.default_connection` service directly.

@Ocramius Is there any chance `doctrine.dbal.default_connection` is required somewhere inside of doctrine by some reasons?

**Comment by cris2018cris** [comment] 2018-05-15 08:58
a question i try to move symfony to heroku,  in local works fine but when i deplay on heroku i found this error ... ```
In ConnectionFactory.php line 96:
                                                                                      
         An exception occured while establishing a connection to figure out your pla  
         tform version.                                                               
         You can circumvent this by setting a 'server_version' configuration value    
                                                                                      
         For further information have a look at:                                      
         https://github.com/doctrine/DoctrineBundle/issues/673 
```

what is the solution?

 thanks

**Comment by cris2018cris** [comment] 2018-05-15 13:18
maybe the solution is      path: 'php://stderr'

**Comment by lutonda** [comment] 2018-09-01 05:50
I soved doing like this

`doctrine:
    dbal:
        default_connection: prod
        connections:
             prod:
                  server_version: 9.4
                  driver: pdo_mysql
                  host: "%database_host%"
                  port: "%database_port%"
                  dbname: "%database_name%"
                  user: "%database_user%"
                  password: "%database_password%"
                  charset: UTF8
                  mapping_types:
                      uuid_binary: binary`

**Comment by pfleu** [comment] 2018-09-12 11:28
@lutonda Thanks for your solution ! How did you get the server_version value ?

**Comment by lutonda** [comment] 2018-09-13 14:26
I'm using debian, just run
mysql -V

**Comment by TrafDmitry** [comment] 2019-05-23 09:32
I have same problem with symfony 4 + postgrqs 9.6, "server_version" it work for me, in my doctrine.yaml.Thanks.

**Comment by NiklasBr** [comment] 2019-07-09 07:08
@aguidis when using your example I encountered the following error:

```
In DBALException.php line 76:
                                                                               
  Invalid platform version "'5.7'" specified. The platform version has to be   
  specified in the format: "<major_version>.<minor_version>.<patch_version>".  
```

Changing from this:
```yml
server_version: '5.7' # Dark magic here
```
to this:
```yml
server_version: 5.7.0 # Dark magic here
```
Appears to have fixed my issue.

**Comment by justbane** [comment] 2019-07-18 17:19
This is a huge problem for me - I am running into this issue on install and server_version is not allowed in the installer.yml (version ~5.8.0)

Where would you identify the server_version in order to run the installer?

**Comment by nmateo** [comment] 2019-09-09 13:05
Hello i have the same issue it seems that i need to specify my doctrine dbal server_version, but i can't find where, here is a tree of my project..:

.
├── app
│   ├── AppCache.php
│   ├── AppKernel.php
│   ├── AppKernel.php~
│   ├── config
│   │   ├── config_dev.yml
│   │   ├── config_dev.yml~
│   │   ├── config_prod.yml
│   │   ├── config.yml
│   │   ├── override
│   │   │   ├── config.yml
│   │   │   ├── routing.yml
│   │   │   ├── Services
│   │   │   │   ├── entities_manager.yml
│   │   │   │   └── forms.yml
│   │   │   └── services.yml
│   │   ├── parameters.yml
│   │   ├── parameters.yml~
│   │   ├── parameters.yml.dist
│   │   ├── routing.yml
│   │   ├── rsync_exclude.txt
│   │   ├── security.yml
│   │   └── services.yml
│   ├── console
│   └── Resources
│       └── views
│           └── base.html.twig
├── auth.json
├── auth.json.dist
├── bin
│   ├── behat -> ../vendor/behat/behat/bin/behat
│   ├── console
│   ├── cssmin -> ../vendor/tubalmartin/cssmin/cssmin
│   ├── doctrine -> ../vendor/doctrine/orm/bin/doctrine
│   ├── doctrine-dbal -> ../vendor/doctrine/dbal/bin/doctrine-dbal
│   ├── doctrine-migrations -> ../vendor/doctrine/migrations/bin/doctrine-migrations
│   ├── php-parse -> ../vendor/nikic/php-parser/bin/php-parse
│   ├── phpunit -> ../vendor/phpunit/phpunit/phpunit
│   ├── security-checker -> ../vendor/sensiolabs/security-checker/security-checker
│   ├── selenium-head
│   ├── selenium-headless
│   ├── simple-phpunit -> ../vendor/symfony/phpunit-bridge/bin/simple-phpunit
│   ├── symfony_requirements
│   └── update-app
├── CODING_STANDARD.md
├── composer.json
├── composer.lock
├── composer.phar
├── doc
├── features
├── LICENSE
├── packages.json.dist
├── phpmd.xml

This is taking me hours...

**Comment by stof** [comment] 2019-09-09 15:24
well, probably in `app/config/config.yml`. Look at where you are configuring the other Doctrine settings.

**Comment by dorthrithil** [comment] 2020-12-08 08:15
My solution was to just start my database server. -___- Really confusing error message for such a simple problem.

**Comment by sarah-quinn** [comment] 2025-11-12 22:49
Ran into this issue on PS 8.2.3, I did literally nothing on the website (not sure if the provider did any changes though). It was a flash from a clear sky. In my case I changed the server address in parameters.php from '127.0.0.1' to 'localhost' and cleared var/cache. Hopefully, it helps someone. Very strange.

**Comment by ShivamJoker** [comment] 2026-08-27 10:09
I enabled password rotation in AWS and it changed the password again hence this error.
