### ISSUE TITLE
Metadata Factory in Entity Manager no longer uses the Resolve Target Entities with 2.3 Version

### ISSUE THREAD

**Issue by francoispluchino** [doctrine/DoctrineBundle#1308] opened 2021-03-23 10:15 UTC
After updating from version 2.2.4 to version 2.3.0, the Metadata Factory of the Entity Manager no longer uses the Resolve Target Entities to check whether the name of a class is present or not.

In Dev environment, this works correctly, on the other hand in Prod environment and only with version 2.3.0, none of the Object Managers find the requested class.

**Example:**

```yaml
# YAML config
doctrine:
    orm:
        resolve_target_entities:
            App\Model\FooInterface: App\Entity\Foo
```

```php
use App\Model\FooInterface;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\Persistence\ObjectManager;

/**
 * @throws \Exception When manager is not found for the target class name
 */
function example(ManagerRegistry $registry, string $targetClassName): ObjectManager
{
    foreach ($this->registry->getManagers() as $objectManager) {
        if ($objectManager->getMetadataFactory()->hasMetadataFor($targetClassName)) {
            return $objectManager;
        }
    }
    
    throw new \Exception(sprintf('Unable to find the object manager associated with an entity of class "%s".', $targetClassName));
}

/** @var ManagerRegistry $doctrineRegistry */
$om = example($doctrineRegistry, FooInterface::class);
```

Given that a difference between dev and prod environment, I guess this is not an expected behavior. However, I tried to find a fix in the short time I have, but it was not successful.

**Comment by ostrolucky** [comment] 2021-03-23 10:18
@ossinkine can you please check if this is because of your changes in https://github.com/doctrine/DoctrineBundle/pull/1260?

**Comment by dmaicher** [comment] 2021-03-24 16:50
I just tried this on one of my apps and I can confirm that there is something odd happening.

I tried this small php script on my Symfony 4.4 app:

```php
<?php

require_once 'vendor/autoload.php';

$kernel = new AppKernel('dev', true);
$kernel->boot();

dump($kernel->getContainer()->get('doctrine')->getManager()->getMetadataFactory()->hasMetadataFor('App\Model\FooInterface'));
```

and also adding a mapping via `resolve_target_entities`.

For me this works **only** on the first execution if there is no cache yet and it fails on the second execution with warmed up cache:

```
$ rm -rf app/cache/*
$ php test.php 
test.php on line 8:
true
$ php test.php 
test.php on line 8:
false
``` 

This fails on `dev` and `prod` env and also with or without debug - does not make a difference.

**And this fails with DoctrineBundle 2.2.4 and also with 2.3.0 for me. No difference.**

**Comment by dmaicher** [comment] 2021-03-24 17:11
Ah @francoispluchino actually `ClassMetadataFactory::hasMetadataFor` is not meant for checking if meta data could be loaded for the given className or not... 

See phpdoc: https://github.com/doctrine/persistence/blob/2.1.x/lib/Doctrine/Persistence/Mapping/ClassMetadataFactory.php#L32

It returns `true` when the metadata was already loaded and always `false` otherwise.

**Comment by ossinkine** [comment] 2021-03-24 17:17
@dmaicher I've reproduced the issue, just call `getAllMetadata` before `hasMetadataFor` in your example

**Comment by stof** [comment] 2021-03-24 17:19
the right fix is not that. It is to use `isTransient` instead of `hasMetadataFor`

**Comment by ostrolucky** [comment] 2021-03-24 17:20
Is this a doctrine-bundle bug, or not?

**Comment by stof** [comment] 2021-03-24 17:22
the fact that `hasMetadataFor` does not do what its name suggest ? No. That's a WTF API in the ORM, but it behaves like the phpdoc says.

**Comment by ostrolucky** [comment] 2021-03-24 17:24
Cool. Let's close this issue then?

**Comment by ossinkine** [comment] 2021-03-24 17:28
Maybe using method `hasMetadataFor` in this case is incorrect, but the fact that method `hasMetadataFor` returns different values on the first call when the cache is warming up, and on the second one, when the cache is already warmed up, it is clearly an error

**Comment by dmaicher** [comment] 2021-03-24 17:42
@ossinkine indeed I can reproduce it like this

```php
<?php

require_once 'vendor/autoload.php';

$kernel = new AppKernel('dev', false);
$kernel->boot();

$kernel->getContainer()->get('doctrine')->getManager()->getMetadataFactory()->getAllMetadata();
dump($kernel->getContainer()->get('doctrine')->getManager()->getMetadataFactory()->hasMetadataFor('App\Model\FooInterface'));
``` 

works fine on first execution without cache and fails afterwards on 2.3.0 when using `debug=false` (so new caching mechanism).

**Comment by dmaicher** [comment] 2021-03-25 21:53
@ossinkine actually my reproducer above was not quite correct as for the `dev` environment I was not using any persistent cache at all with DoctrineBundle 2.2.4 (even debug=0 was using `ArrayCache`).

So I tried this again using `prod` env which was using a `cache.system` based cache pool like in the [recipe](https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.12/config/packages/prod/doctrine.yaml#L6) on DoctrineBundle 2.2.4.

**=> this fails for me on 2.2.4 and also on 2.3.0.** Exact same behavior.

It fails with any persistent cache. For example a `FilesystemCache`:

```php
<?php

use Doctrine\Common\Cache\FilesystemCache;
use Doctrine\Persistence\Mapping\AbstractClassMetadataFactory;

require_once 'vendor/autoload.php';

$kernel = new AppKernel('prod', false);
$kernel->boot();

/** @var AbstractClassMetadataFactory $metadataFactory */
$metadataFactory = $kernel->getContainer()->get('doctrine')->getManager()->getMetadataFactory();

$metadataFactory->setCacheDriver(new FilesystemCache('/tmp/doctrine-cache'));
$metadataFactory->getAllMetadata();

dump($metadataFactory->hasMetadataFor('App\Model\FooInterface'));
``` 

==> 

```
$ rm -rf /tmp/doctrine-cache/*
$ php test.php 
^ true
$ php test.php 
^ false
``` 

So to me does not look related to https://github.com/doctrine/DoctrineBundle/pull/1260.

@francoispluchino which caching config are you using for the metadata cache on your prod environment?

**Comment by francoispluchino** [comment] 2021-03-26 08:50
@dmaicher 

After a few tests, and without moving the environment into prod (therefore staying in a dev environment), it suffices to activate only the Doctrine metadata cache with the default configuration:

```yaml
# config/packages/dev/doctrine.yaml
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool

framework:
    cache:
        pools:
            doctrine.system_cache_pool:
                adapter: cache.system
```

For the example, the Symfony cache configuration uses the Flex recipe, so the file cache (in `var/cache/dev/pools/*`).

Result:
- The first call: `hasMetadataFor('App\Model\FooInterface') === true`
- The second call: `hasMetadataFor('App\Model\FooInterface') === false`

**Comment by dmaicher** [comment] 2021-03-26 10:08
@francoispluchino and this also fails using DoctrineBundle 2.2.4, or? It should not make a difference if using 2.3.0 or 2.2.4 I believe.

**Comment by ossinkine** [comment] 2021-03-30 15:25
I've double checked this and agree with @dmaicher, I got the same  result, this behavior doesn't related to the new cache system and wasn't changed since 2.2.4.
Actually @stof already answered a week ago, please use `isTransient` instead of `hasMetadataFor`.

**Closed as completed** 2021-03-30 16:23 UTC
