### ISSUE TITLE
Can't drop PostgreSQL database

### ISSUE THREAD

**Issue by davialexandre** [doctrine/DoctrineBundle#402] opened 2015-03-07 03:12 UTC
It started after commit 1ed0fecc583fe7bc2e4b9b101dafa52bf8c63ca9. When you try to connect to PostgreSQL without a dbname, the username is used instead. If you don't have a database with same name as the username the connection will fail (and if both, the username and the database that you're trying to drop, have the same name the drop will also fail).

After a few tests, I don't think this can be fixed in DropDatabaseDoctrineCommand. I think that maybe the solution would change Doctrine\DBAL\Driver\PDOPgSql\Driver::_constructPdoDsn to use some default  database name (maybe postgres) if dbname isn't set, but I have no idea if this would impact somewhere else.

**Comment by phansys** [comment] 2015-04-09 14:35
I opened a [issue in PHP](https://bugs.php.net/bug.php?id=67431) some time ago because I didn't know that this was the expected behavior.

**Comment by deeky666** [comment] 2015-04-10 08:05
@davialexandre can we rely on `postgres` DB being always present? Is it possible to not have that DB in a server setup? I agree that we might need to add some abstraction around this issue to DBAL if it cannot be fixed this way...

**Comment by davialexandre** [comment] 2015-04-14 01:57
The `postgres` database is always created by the initdb command, but it can be dropped. This command also creates the `template1` database, that is a template for other databases. Templates cannot be dropped, so I believe it is a good candidate as a default database name

**Comment by steve-todorov** [comment] 2015-04-14 23:20
@deeky666, @davialexandre is right. I've commented on your [pull request](https://github.com/doctrine/DoctrineBundle/pull/368#issuecomment-90983299) a while ago with observations and a possible solution to this issue. The same approach is used in PhpPGAdmin and I haven't had any issues in the past 3-4 years or so. 

Also, the documentation of PostgreSQL points out that you'll always have a `template0` and `template1` database ([more here](http://www.postgresql.org/docs/9.1/static/manage-ag-templatedbs.html)) so this approach should be safe to use.

**Comment by kiwidg** [comment] 2015-04-29 16:17
Same problem here. I agree to say that template1 is a good default database, and thus used it in my [PR](https://github.com/doctrine/dbal/pull/844).

**Comment by steve-todorov** [comment] 2015-04-29 23:54
Neat solution! @stof @deeky666 - whenever you have some time, could you please have a look at this and merge it if everything's ok? :)

**Comment by kiwidg** [comment] 2015-04-30 11:26
@steve-todorov I actually think that https://github.com/steve-todorov/DoctrineBundle/commit/113ebec1252242639c242c2fab0263ac41e9cc89 is a better solution, as it deals with the unfortunate "feature" of PostgreSQL instead of hiding it through DBAL. Could you please rebase, create a specific branch and pull-request ? I will close my PR for dbal as soon as yours is opened for DoctrineBundle.

**Comment by deeky666** [comment] 2015-04-30 16:41
@davialexandre @kiwidg @steve-todorov I merged the DBAL patch. Should be working with DBAL master now. Can someone confirm, please?
Also backported the fix to 2.5 and 2.4 branches.

**Comment by kiwidg** [comment] 2015-05-04 13:29
@deeky666 It works, for creating and dropping a database (with dev-master). Do you have an ETA for a v2.5.2 tag with the fix ?

**Comment by acasademont** [comment] 2015-05-28 14:40
Yep, a 2.5.2 tag would come handy :D @deeky666

**Comment by vpassapera** [comment] 2015-08-18 06:20
Ping....any word on this?

**Comment by trylika** [comment] 2015-09-04 11:16
Ping again, release would really help

**Comment by deeky666** [comment] 2015-09-04 17:44
Sorry guys didn't see the comments. Will tag a new version next week. Sorry for the delay

**Comment by Ph3nol** [comment] 2015-09-10 07:33
Waiting for a 2.5.2 tag too. :+1: 
Thank you!

**Comment by deeky666** [comment] 2015-09-16 16:42
New tag is available: https://github.com/doctrine/dbal/releases/tag/v2.5.2

**Comment by pdesgarets** [comment] 2015-09-21 21:35
Thanks @deeky666 !

**Comment by kimhemsoe** [comment] 2015-09-21 21:52
Reading from comments this issue should be solved with the tagging of a new dbal release, therefor i am closing this.

**Closed by kimhemsoe** 2015-09-21 21:52 UTC
