### ISSUE TITLE
Change charset on Column

### ISSUE THREAD

**Issue by AntoineLemaire** [doctrine/DoctrineBundle#844] opened 2018-08-28 08:54 UTC
I'm using the `options` to set a different charset for my `message` column

    /**
     * @var string
     *
     * @ORM\Column(name="message", type="text", nullable=false, options={"charset":"utf8mb4", "collation":"utf8mb4_unicode_ci"})
     */
    private $message;

When I run `app/console doctrine:schema:update --dump-sql --force`, it successfully update my DB
```
 The following SQL statements will be executed:

     ALTER TABLE mytable CHANGE message message LONGTEXT  NOT NULL COLLATE utf8mb4_unicode_ci;
```

But if I run again `app/console doctrine:schema:update --dump-sql`, it still propose me to update the same table with the same query

Is that a bug, or did I do something wrong?

**Comment by Tobion** [comment] 2018-11-05 15:13
Duplicate of https://github.com/doctrine/dbal/pull/2401 and https://github.com/doctrine/dbal/issues/2538

**Comment by alcaeus** [comment] 2018-11-15 08:13
Thanks @Tobion. Closing here.

**Closed by alcaeus** 2018-11-15 08:13 UTC
