### ISSUE TITLE
Symfony Command Line Application and Doctrine: ERROR - Notice: Undefined index:

### ISSUE THREAD

**Issue by sinner** [doctrine/DoctrineBundle#1018] opened 2019-09-15 12:17 UTC
Hi Symfony Community! Thank you very much in advance.

I have an API that receives a CSV file to import some registers but this task is queued using Amazon SQS, so it's an asynchronous task made using the Symfony Console Component who is loading that data.

This command-line application made using the Symfony Console Component uses Doctrine to store all registers read from that CSV file, so when it starts the first register is loaded perfectly into my PostgreSQL (AWS-RDS) database, but after that first register the next tries aren't loaded to the database giving the following exception "Undefined index: 000000004fc9e3630000000009549173" just after executing the flush method, here is a bit of the track-trace of the exception:

```logs
...
"exceptionMessage" => "Notice: Undefined index: 000000004fc9e3630000000009549173"
  "exceptionTrace" => array:19 [
    0 => array:6 [
      "file" => "/srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php"
      "line" => 677
      "function" => "getEntityIdentifier"
      "class" => "Doctrine\ORM\UnitOfWork"
      "type" => "->"
      "args" => array:1 [
        0 => Proxies\__CG__\App\Entity\Member {#9112
          +__isInitialized__: false
          -id: 1
          -firstName: null
          -lastName: null
          -birthDate: null
          -profilePictureUrl: null
          -occupation: null
          -stateText: null
          -stateIsoCode: null
          -cityText: null
          -postalCode: null
          -referenceAddress: null
          -deceasedAt: null
          -status: null
          -roles: null
          -user: App\Entity\User {#9103
            #id: 2315
            #publicId: "ac41571d1fcbb25901b6ad030623abccfd8390fc"
            #username: "admin"
            #displayName: "Cory Taylor"
            #email: "teramailtest+admin@gmail.com"
            -temporaryOrgAdmin: false
            -alreadyHasGroupAdminRole: true
            -alreadyHasOrgAdminRole: true
            -birthdaysThisWeek: true
            -newMessageReplies: true
            -groupActivityStatus: true
            -hasEmail: false
            -mainRole: ""
            -realMainRole: ""
            #displayEmail: null
            #createdAt: DateTime @1568315992 {#13576
              date: 2019-09-12 19:19:52.971833 UTC (+00:00)
            }
            #roles: array:5 [
              0 => "ROLE_ADMIN"
              1 => "ROLE_SUPER_ADMIN"
              2 => "ROLE_ORGANIZATION_ADMIN"
              3 => "ROLE_EVA_GROUP_ADMIN"
              4 => "ROLE_EVA_MEMBER"
            ]
            #updatedAt: DateTime @1568315992 {#13576}
            #member: Proxies\__CG__\App\Entity\Member {#9112 …2}
            -languagePreference: Proxies\__CG__\App\Entity\Language {#9107
              +__isInitialized__: false
              -id: 40
              -name: null
              -iso: null
              -flag: null
              -enable: null
              #publicId: null
              #createdBy: null
              #updatedBy: null
              #dateCreated: null
              +referenceProxies: []
              #createdAt: null
              #updatedAt: null
               …2
            }
            -isVerifiedEmail: false
            #plainPassword: null
            #isIncomplete: null
            #mpaToken: null
            #mpaUserId: 166989
            +referenceProxies: []
            -termAndConditionAcceptances: Doctrine\ORM\PersistentCollection {#9108
              -snapshot: []
              -owner: App\Entity\User {#9103}
              -association: array:15 [ …15]
              -em: Doctrine\ORM\EntityManager {#224 …11}
              -backRefFieldName: "acceptedBy"
              -typeClass: Doctrine\ORM\Mapping\ClassMetadata {#8525 …}
              -isDirty: false
              #collection: Doctrine\Common\Collections\ArrayCollection {#9109
                -elements: []
              }
              #initialized: false
            }
            #usernameCanonical: "admin"
            #emailCanonical: "teramailtest+admin@gmail.com"
            #enabled: true
            #salt: null
            #password: "$2y$13$utOmgjkEMw8jahFnHEo51esv5N7g81X4cCPwrlLgfNnF5HljLR2jS"
            #lastLogin: DateTime @1567721304 {#6980
              date: 2019-09-05 22:08:24.0 UTC (+00:00)
            }
            #confirmationToken: "a72189fa2d8099376ca708f0eb5bb92e4e593ce8"
            #passwordRequestedAt: null
            #groups: null
          }
          -family: null
          -religion: null
          -ethnicity: null
          -grade: null
          -country: null
          -state: null
          -city: null
          -phones: null
          -mainPhone: null
          -addresses: null
          -tags: null
          -skills: null
          -organizations: null
          -groups: null
          -declinedGroupMembers: null
          -sentMessages: null
          -readMessages: null
          -archivedMessages: null
          -tips: null
          -notifications: null
          -messageReplyNotifications: null
          -notificationsDismissed: null
          -tipsDismissed: null
          -receivedMessages: null
          -receivedArchivedMessages: null
          -folderTemplatesSharedWithMe: null
          -underAge: null
          -MPAUserId: 0
          -MPAAuthenticationToken: null
          -email: null
          -hasEmail: false
          -mainPhoneNumber: null
          -messageDeliveredMetrics: null
          #publicId: null
          #createdBy: null
          #updatedBy: null
          #dateCreated: null
          +referenceProxies: []
          #createdAt: null
          #updatedAt: null
           …2
        }
      ]
    ]
    1 => array:6 [
      "file" => "/srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php"
      "line" => 713
      "function" => "prepareUpdateData"
      "class" => "Doctrine\ORM\Persisters\Entity\BasicEntityPersister"
      "type" => "->"
      "args" => array:1 [
        0 => App\Entity\User {#9103}
      ]
    ]
    2 => array:6 [
      "file" => "/srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php"
      "line" => 275
      "function" => "prepareInsertData"
      "class" => "Doctrine\ORM\Persisters\Entity\BasicEntityPersister"
      "type" => "->"
      "args" => array:1 [
        0 => App\Entity\User {#9103}
      ]
    ]
    3 => array:6 [
      "file" => "/srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php"
      "line" => 1073
      "function" => "executeInserts"
      "class" => "Doctrine\ORM\Persisters\Entity\BasicEntityPersister"
      "type" => "->"
      "args" => []
    ]
    4 => array:6 [
      "file" => "/srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php"
      "line" => 386
      "function" => "executeInserts"
      "class" => "Doctrine\ORM\UnitOfWork"
      "type" => "->"
      "args" => array:1 [
        0 => Doctrine\ORM\Mapping\ClassMetadata {#103
          +name: "App\Entity\User"
          +namespace: "App\Entity"
          +rootEntityName: "App\Entity\User"
          +customGeneratorDefinition: null
          +customRepositoryClassName: "App\Entity\Repository\UserRepository"
          +isMappedSuperclass: false
          +isEmbeddedClass: false
          +parentClasses: []
          +subClasses: []
          +embeddedClasses: []
          +namedQueries: []
          +namedNativeQueries: []
          +sqlResultSetMappings: []
          +identifier: array:1 [
            0 => "id"
          ]
...
```

This address to us to put a dump into this class "/srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:677" to see what indexes were being generated, and actually we were reviewing that the index of the error wasn't part of the array of indexes array prepared to update/insert registers into the database and those indexes are generated from some Proxy/Entity classes that are generated dynamically and updated after we are executing the same command-line application.

Has somebody seen that error before? I've opened an issue because I didn't see this in other issues I've been reading, moreover, I've found another reference of the error in this page:

https://www.oipapio.com/question-537301

I've tried to solve all the warnings of relation references into my entity files but it didn't solve the problem. I hope you could help me.

This is my package.json for you to be able to se the version the framework we are using:

```json
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "bhaktaraz/php-rss-generator": "dev-master",
        "bugsnag/bugsnag-symfony": "^1.5",
        "csa/guzzle-bundle": "^3.0",
        "egulias/email-validator": "^2.1",
        "endroid/twitter": "^2.0",
        "enqueue/sqs": "^0.8.40",
        "ezyang/htmlpurifier": "^4.10",
        "facebook/graph-sdk": "^5.6",
        "friendsofsymfony/elastica-bundle": "^5.0",
        "friendsofsymfony/oauth-server-bundle": "^1.6",
        "friendsofsymfony/rest-bundle": "^2.3",
        "friendsofsymfony/user-bundle": "~2.0",
        "fzaninotto/faker": "^1.7",
        "gaufrette/aws-s3-adapter": "^0.4.0",
        "guzzlehttp/guzzle": "^6.3",
        "jms/serializer-bundle": "^2.3",
        "knplabs/gaufrette": "^0.6.0",
        "knplabs/knp-gaufrette-bundle": "^0.5.3",
        "league/csv": "^9.0",
        "lexik/jwt-authentication-bundle": "^2.4",
        "narendravaghela/bitly-client": "^1.0",
        "nelmio/api-doc-bundle": "^3.2",
        "nelmio/cors-bundle": "^1.5",
        "oro/doctrine-extensions": "^1.2",
        "pelago/emogrifier": "^2.1",
        "php-amqplib/rabbitmq-bundle": "^1.14",
        "plivo/php-sdk": "4.1.3",
        "predis/predis": "^1.0",
        "sensio/framework-extra-bundle": "^5.1",
        "sensiolabs/security-checker": "^4.1",
        "shortpixel/shortpixel-php": "^1.5",
        "snc/redis-bundle": "2.1.3",
        "symfony/asset": "^4.0",
        "symfony/cache": "^4.0",
        "symfony/console": "^4.0",
        "symfony/dom-crawler": "^4.0",
        "symfony/expression-language": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/messenger": "^4.0",
        "symfony/monolog-bundle": "^3.3",
        "symfony/orm-pack": "^1.0",
        "symfony/profiler-pack": "^1.0",
        "symfony/proxy-manager-bridge": "^4.0",
        "symfony/serializer-pack": "^1.0",
        "symfony/swiftmailer-bundle": "^3.2",
        "symfony/twig-bundle": "^4.0",
        "symfony/validator": "^4.0",
        "symfony/var-dumper": "^4.0",
        "symfony/yaml": "^4.0",
        "tgalopin/html-sanitizer": "^1.2",
        "white-october/pagerfanta-bundle": "^1.2"
    },
    "require-dev": {
        "behat/behat": "^3.4",
        "behat/mink": "^1.7",
        "behat/mink-browserkit-driver": "^1.3",
        "behat/mink-extension": "^2.3",
        "behat/symfony2-extension": "^2.1",
        "behatch/contexts": "^3.1",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "symfony/browser-kit": "^4.0",
        "symfony/dotenv": "^4.0",
        "symfony/maker-bundle": "^1.4",
        "phpunit/phpunit": "^7.0",
        "symfony/phpunit-bridge": "^4.0",
        "symfony/web-server-bundle": "^4.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false
        }
    }
}
```

**Comment by greg0ire** [comment] 2019-10-16 19:13
Closing as duplicate of https://github.com/doctrine/orm/issues/7817

**Closed by greg0ire** 2019-10-16 19:13 UTC
