### ISSUE TITLE
The runnable query in the profiler breaks on comment

### ISSUE THREAD

**Issue by stof** [doctrine/DoctrineBundle#195] opened 2013-07-08 17:55 UTC
As the runnable query looses the newlines of the original query, it is broken when the original query contains a SQL comment (which can happen for hand-written SQL queries).
It is an edge case though as most queries in the profiler are generally coming from the ORM which does not add comments

**Comment by javiereguiluz** [comment] 2016-03-21 10:23
Can anyone check if this bug still persists after all these years? Thanks!

**Comment by stof** [comment] 2016-03-21 11:33
As the runnable query is still not displayed in a ``<pre>`` to preserve wrapping of newlines, it is still an issue yes.

**Comment by javiereguiluz** [comment] 2016-03-21 11:40
I'm missing something here. The runnable query is displayed inside a `<pre>` element:

![runnable_query](https://cloud.githubusercontent.com/assets/73419/13917535/cc790b9e-ef61-11e5-9b98-277a0869a4ca.png)

It's true that this query doesn't preserve the original new lines. But that's because it would take too much space and because we already do that for the *View formatted query* option.

**Comment by stof** [comment] 2016-03-21 11:42
Well, actually, that's because of the highlighting. SqlFormatter drops the original newlines to add its own ones when highlighting

**Comment by javiereguiluz** [comment] 2016-03-21 11:43
OK. I understand now. Thanks.

**Comment by stof** [comment] 2016-03-21 11:43
btw, ``View formatted query`` does not preserve the original newlines. It adds newlines for formatting (with much more newlines than in the original query in general, as the way to get more newlines would be to put them between each word in the query, which is not done by any sane SQL author)

**Comment by ostrolucky** [comment] 2019-12-07 23:30
Looks like this got meanwhile fixed, as I cannot reproduce it.
```php
$conn->exec('
        SELECT * -- comment1
        FROM /* comment2 */ symfony_demo_post');
```
<img width="511" alt="Screenshot 2019-12-08 at 00 28 15" src="https://user-images.githubusercontent.com/496233/70381827-a5078400-1951-11ea-9215-8057fcc16165.png">

Closing, will reopen again when posted some reproducer

**Closed by ostrolucky** 2019-12-07 23:30 UTC
Labels: Bug, Ready to work on
