### ISSUE TITLE
And response:Entity has to be managed or scheduled for removal for single computation App\Entity\StatisticsActiveRecord@0000000012d56eff000000001623c91a

### ISSUE THREAD

**Issue by followyounger** [doctrine/DoctrineBundle#994] opened 2019-07-11 11:03 UTC

**Comment by xabbuh** [comment] 2019-07-11 12:32
I am sorry, but without more information, we won't be able to help you with this.

**Comment by followyounger** [comment] 2019-07-12 08:12
maybe this exceptions is caused by the cache of symfony?
after i redeploy the program, this exception is disappear.

**Comment by followyounger** [comment] 2019-07-12 08:16
and i find a entity, and change some fields of this entity, and persist and flush it, it is not do the UPDATE this entity, but INSERT it. it dues to duplicate unique key. so i have to get the Throwable exception, and update this entity in the catch place.

can you help me ?

**Comment by followyounger** [comment] 2019-07-12 08:17
thank you so much

**Comment by xabbuh** [comment] 2019-07-12 13:03
As I said before without being able to reproduce the behaviour you experience it will be hard to help you.

**Comment by followyounger** [comment] 2019-07-13 08:32
$user = $this->userActiveRecordRepository->findOneBy(['deviceId' => $deviceId4Md]);、
$user->setUserId($userId);
$user->setRegisterTime(\DateTime::createFromFormat('Y-m-d H:i:s', $userCreateTime));
$this->reconnectEntityManager();
$this->entityManager->persist($user);
$this->entityManager->flush();



   public function reconnectEntityManager() {
        if (!$this->entityManager->isOpen()) {
            $this->entityManager = $this->entityManager::create(
                $this->entityManager->getConnection(),
                $this->entityManager->getConfiguration()
            );
        }
    }


and i do not know why and where the entityManager is closed, so i have to test the state of entityManager. maybe it is caused by the delay of master and slave of mysql? and it is caused some exception.

**Comment by SenseException** [comment] 2019-07-22 19:59
Can you please format your code with markdown to make it more readable?

`$user->setUserId($userId);` - Do you change your primary-key here? This might result in an error message you describe in the title in case you're doing this.

**Comment by PReimers** [comment] 2019-11-23 14:22
@followyounger is this still an issue?

**Comment by followyounger** [comment] 2019-11-25 03:45
> @followyounger is this still an issue?

yes man, i have fixed it, thx

**Comment by PReimers** [comment] 2019-11-25 05:17
@followyounger since you fixed it.

Would you want to let us know how you fixed it, or should we just close this issue?

**Comment by ostrolucky** [comment] 2019-12-01 15:01
This doesn't look like issue in bundle. Combined with the fact OP does no longer respond, this is inactionable. Closing here

**Closed by ostrolucky** 2019-12-01 15:01 UTC
