### ISSUE TITLE
[BUG] An error occurred while loading the query explanation.

### ISSUE THREAD

**Issue by mehranhadidi** [doctrine/DoctrineBundle#830] opened 2018-07-03 07:52 UTC
I think there must be a bug on query explanation doctrine. 

Doctrine ^1.6
Symfony 4.1.1

I have a simple find query with doctrine. When I run my code everything works just fine. But when I try to run query explain on profiler there is the error:

An error occurred while loading the query explanation.

I have googled it and a lot of people have the same issue. But there is no fix. Any solution?

**Comment by Ocramius** [comment] 2018-07-03 07:58
Closing here - please open a new issue with more detailed information, examples, as well as what has been attempted so far, including tests that were written to uncover the issue.

**Closed by Ocramius** 2018-07-03 07:58 UTC

**Comment by mehranhadidi** [comment] 2018-07-03 08:15
@Ocramius This is just a simple find query. Its also working well but the issue is related to **query explanation**

Does it really needs to tests?? 

![image](https://user-images.githubusercontent.com/897774/42207327-ed99f9de-7ebe-11e8-95f7-a37a29f1f68e.png)

**Comment by Ocramius** [comment] 2018-07-03 08:29
Well, it surely needs more debugging and searching for a root cause before reporting an issue 👍

**Comment by mehranhadidi** [comment] 2018-07-03 10:37
Its a fresh Symfony project without any specific dependency that runs a simple select by 1 query. That's all.

**Comment by Ocramius** [comment] 2018-07-03 10:39
Yes: as I said, report a bug after: 

 1. having identified a way to reproduce it precisely (steps that someone reading the issue can follow)
 2. what is expected
 3. what happens instead
 4. what has been attempted to fix the problem
 5. a test case that reproduces the bug, once identified

**Comment by Ocramius** [comment] 2018-07-04 07:30
> It looks like you just don't want to even try to listen

Mostly just struggling with all the issues being juggled, hence the request for more details, as well as isolated scenarios. No malice intended, just be aware that I answer a dozen of these a day, and only get to look at anything ince it's already well distilled.

> Do you want me to share my code as a GitHub repository?

If you think sharing a repository would be the easiest reproducer, sure. The ideal case would be a setup from the first clone of the exact distribution and version of symfony you are using, and what you did from then on (line-by-line).

**Comment by mehranhadidi** [comment] 2018-07-04 08:11
All right. I will try my best to reproduce the issue step by step with detailed information.

**Comment by yceruto** [comment] 2018-07-04 14:58
FYI this was fixed in https://github.com/doctrine/DoctrineBundle/pull/802, merged but not released yet.
